version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/frontend
    overwrite: yes
permissions:
  - object: /home/ubuntu/app/frontend
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root