version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/stock-community-frontend
    overwrite: yes
permissions:
  - object: /home/ec2-user/app/stock-community-frontend
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root